version: '3'
services:
#   backend:
#     build: ./backend
#     ports:
#       - "8080:8080"
#     environment:
#       - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskdb
#       - SPRING_DATASOURCE_USERNAME=postgres
#       - SPRING_DATASOURCE_PASSWORD=postgres
#     depends_on:
#       - db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
